import {
  BadgeCheck,
  BriefcaseBusiness,
  Factory,
  FlaskConical,
  Handshake,
  Leaf,
  Network,
  ShieldCheck,
  Sprout,
  TrendingUp,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type IngredientLine = "Functional Probiotics" | "Nature-derived Ingredients";

export type Ingredient = {
  id: string;
  name: string;
  category: string;
  area: string;
  summary: string;
  intake: string;
  image: string;
  strains?: string[];
  origin?: string[];
  healthClaims?: string[];
  featurePoints?: string[];
  evidenceTags: string[];
  line: IngredientLine;
};

export const probioticsIngredients: Ingredient[] = [
  {
    id: "med01",
    name: "iHEAL GINO 5 Formula - MED01",
    category: "女性",
    area: "膣内マイクロバイオーム",
    summary: "健康な韓国女性の膣から分離した特許乳酸菌。女性の膣健康向上プロバイオティクス複合物。",
    intake: "50億 CFU/day (5×10⁹ CFU/day)",
    image: "/images/ingredients/med01.webp",
    strains: [
      "L. plantarum MG989",
      "L. salivarius MG242",
      "L. fermentum MG901",
      "L. paracasei MG4272",
      "L. rhamnosus MG4288",
    ],
    healthClaims: [
      "女性の膣健康向上に役立つプロバイオティクス複合物",
      "膣炎の予防および改善に役立つ",
      "膣内環境の改善",
      "膣炎指標(Nugent score)の改善",
    ],
    featurePoints: [
      "健康な韓国女性の膣から分離した100%ヒト由来プロバイオティクス",
      "101名対象のヒト適用試験完了(19歳〜50歳、可妊期女性)",
      "SCI論文9編",
      "国際特許保有(韓国・米国・欧州)、日本特許出願中",
      "膣内乳酸菌の増殖と有害菌の抑制、膣内細菌叢の正常化に役立つ資料",
      "膣分泌物の減少、膣灼熱感の減少、排尿痛の減少",
    ],
    evidenceTags: ["101名ヒト臨床試験", "SCI論文9編", "国際特許3か国"],
    line: "Functional Probiotics",
  },
  {
    id: "med02",
    name: "iHEAL DIT 2 Formula - MED02",
    category: "体脂肪",
    area: "体脂肪・抗肥満プロバイオティクス",
    summary: "健康な韓国人由来の特許乳酸菌。脂肪細胞分化抑制のためのプロバイオティクス。",
    intake: "50億 CFU/day (5×10⁹ CFU/day)",
    image: "/images/ingredients/med02.webp",
    strains: ["L. fermentum MG4231", "L. fermentum MG4244"],
    healthClaims: [
      "脂肪細胞の分化抑制のための特許プロバイオティクス複合物",
      "体重、体脂肪の減少および体質量の減少に役立つ",
    ],
    featurePoints: [
      "健康な韓国人由来の特許乳酸菌",
      "100名対象のヒト適用試験完了(過体重または肥満の成人)",
      "SCI論文6編",
      "国際特許保有(韓国・米国・欧州)",
      "小児期の脂肪細胞分化抑制による小児肥満の減少",
      "脂肪細胞分化抑制による将来の成人肥満発生リスクの減少",
      "成人期の中性脂肪蓄積による肥満・脂質異常症発生リスクの減少",
      "体脂肪量、体脂肪率、体質量(BMI指数)の大幅な減少",
      "臨床データ: 体脂肪量 -1,200g前後(プラセボ -400g前後)、体脂肪率 -0.85%前後(プラセボ -0.15%前後)、体重 -2.1kg前後(プラセボ -1.2kg前後)",
    ],
    evidenceTags: ["100名ヒト臨床試験", "SCI論文6編", "国際特許3か国"],
    line: "Functional Probiotics",
  },
  {
    id: "nvp2106",
    name: "NVP-2106",
    category: "脳・記憶",
    area: "認知・記憶機能",
    summary: "デュオバイオーム技術による脳機能改善用2種特許プロバイオティクス複合物。",
    intake: "100億 CFU/day (10×10¹⁰ CFU/day)",
    image: "/images/ingredients/nvp2106.webp",
    strains: ["L. mucosae NK41", "B. longum NK46"],
    healthClaims: [
      "脳機能改善用特許プロバイオティクス複合物",
      "認知機能改善、記憶力改善に役立つ",
    ],
    featurePoints: [
      "120名対象のヒト適用試験完了(60歳以上、記憶力低下高齢者)",
      "神経細胞損傷と記憶力低下の原因とされる「アミロイドベータ」の調整・低下",
      "認知機能および記憶力の改善",
      "注意集中力の改善",
      "アルツハイマー病評価尺度「ADAS-Cog13」総点の改善",
      "臨床データ(12週摂取, P=0.0318): ADAS-Cog13総点 プラセボ対比202%改善",
      "臨床データ: 記憶力総点 プラセボ対比207%改善(P=0.0257/0.0279)、遅延単語再生 プラセボ対比1,514%改善(P=0.0037)",
      "臨床データ: 注意集中力 正反応数 315%改善、誤反応数147%改善、脱落誤謬数315%改善(P<0.05, 12週)",
    ],
    evidenceTags: ["120名高齢者ヒト臨床試験", "SCI論文参照", "特許複合菌"],
    line: "Functional Probiotics",
  },
  {
    id: "nvp1702",
    name: "NVP-1702 / NVP-17902",
    category: "肝臓",
    area: "肝の健康",
    summary: "デュオバイオーム技術によるアルコール性・非アルコール性肝改善用2種特許プロバイオティクス複合物。",
    intake: "100億 CFU/day (10×10¹⁰ CFU/day)",
    image: "/images/ingredients/nvp1702.webp",
    strains: ["L. plantarum LC27", "B. longum LC67"],
    healthClaims: [
      "アルコール性・非アルコール性肝疾患の改善に役立つプロバイオティクス複合物",
      "血中中性脂肪の改善、肝損傷の改善に役立つ",
    ],
    featurePoints: [
      "93名対象のヒト適用試験完了",
      "体内の肝解毒機能の強化",
      "腸内エンドトキシンおよび血中エンドトキシンの改善",
      "非アルコール性肝損傷: ALT・AST・γ-GTPの改善、疲労指標および血中炎症指標の改善",
      "アルコール性肝損傷: ALT・AST・γ-GTPの改善、血中中性脂肪および血中炎症指標の改善",
      "臨床データ(非アルコール性, 12週): γ-GTP試験群2.85±33.26 U/L減少(対照群24.56±51.11 U/L増加, P=0.0292)、ALT試験群3.77±14.64 U/L減少(対照群5.16±14.46 U/L増加, P=0.0332)",
      "臨床データ(アルコール性, 12週): ALT P=0.0260/0.0397、AST P=0.0131、γ-GTP P=0.0229でプラセボ対比改善",
    ],
    evidenceTags: ["93名ヒト臨床試験", "SCI論文参照", "特許複合菌"],
    line: "Functional Probiotics",
  },
  {
    id: "nvp1703",
    name: "NVP-1703",
    category: "鼻",
    area: "過敏な免疫反応に伴う鼻の状態",
    summary: "デュオバイオーム技術によるアレルギー性鼻炎改善用特許プロバイオティクス複合物。",
    intake: "100億 CFU/day (10×10¹⁰ CFU/day)",
    image: "/images/ingredients/nvp1703.webp",
    strains: ["L. plantarum IM76", "B. longum IM55"],
    healthClaims: [
      "アレルギー性鼻炎改善用特許プロバイオティクス複合物",
      "免疫過敏反応に伴う鼻の状態改善に役立つ",
    ],
    featurePoints: [
      "小児・青少年81名、成人95名の大規模ヒト適用試験完了",
      "小児・青少年: TNSS(全体鼻症状点数)のDaily/Weekly評価で有意な改善、小児鼻炎の改善、炎症調節サイトカインIL-10・IL-22の有意な改善",
      "成人: TNSSのDaily/Weekly評価で有意な改善、水様性鼻水・鼻づまりの改善、鼻炎症状の改善、免疫グロブリンIgEの減少",
    ],
    evidenceTags: ["大規模ヒト臨床試験(小児・成人)", "SCI論文参照", "特許複合菌"],
    line: "Functional Probiotics",
  },
  {
    id: "nvp1704",
    name: "NVP-1704",
    category: "ストレス",
    area: "ストレス・睡眠・リラックス",
    summary: "ストレス性疾患、うつ、不安、不眠症改善用特許プロバイオティクス複合物。",
    intake: "50億 CFU/day (5×10⁹ CFU/day)",
    image: "/images/ingredients/nvp1704.webp",
    strains: ["L. reuteri NK33", "B. adolescentis NK98"],
    healthClaims: [
      "ストレス性疾患、うつ、不安症の改善に役立つ",
      "睡眠の質向上に役立つ",
    ],
    featurePoints: [
      "ストレスを抱える韓国人156名の大規模ヒト適用試験完了",
      "うつ・不安尺度BDI/BAI/BDI+BAIの改善",
      "睡眠の質尺度PSQIおよび不眠症重症度尺度ISIの改善",
      "血液中の炎症性サイトカインIL-6の減少およびBDNFの増加",
      "摂取後の主要構成菌株 L. reuteri群とBifidobacterium群の増加",
    ],
    evidenceTags: ["156名ヒト臨床試験", "睡眠の質指標参照", "特許複合菌"],
    line: "Functional Probiotics",
  },
  {
    id: "bifido",
    name: "Bifidobacterium Probiotics",
    category: "腸",
    area: "腸の健康・排便活動",
    summary: "母乳を与えられた健康な新生児の便由来、100%ヒト由来ビフィズス菌。",
    intake: "用途別設計",
    image: "/images/ingredients/bifido.webp",
    strains: ["B. bifidum BGN4", "B. longum BORI", "B. lactis AD011"],
    healthClaims: [
      "腸の健康と排便活動に役立つ",
      "FDA NDI認証・FDA USP認証プロバイオティクス",
    ],
    featurePoints: [
      "米国食品医薬品局(FDA)安全性認証取得(GRAS・NDI認証取得)",
      "B. bifidum BGN4: GRAS No.814 / NDI No.1079",
      "B. longum BORI: GRAS No.813 / NDI No.1082",
      "B. lactis AD011: GRAS No.952 / NDI No.1118",
      "HALAL認証・KOSHER認証取得",
      "症状別10件のヒト試験保有菌株",
      "80件の国際特許保有",
      "260編以上のSCI論文を保有する世界的なビフィズス菌",
      "12週間摂取後、ガス排出頻度の上昇と腹部膨満感の改善",
      "参考: BGN4・BORIをベースとしたプロバイオティクス(40億CFU/日, 12週間)を65歳以上の高齢者が摂取した試験で、認知機能と気分の改善が腸内マイクロバイオータの変化とともに確認された(ソウル大学校盆唐再生病院実施, J Gerontol A Biol Sci Med Sci. 2021;76(1):32-40)",
    ],
    evidenceTags: ["FDA GRAS/NDI認証", "HALAL/KOSHER認証", "臨床10件・特許80件・SCI論文260編"],
    line: "Functional Probiotics",
  },
];

export const natureIngredients: Ingredient[] = [
  {
    id: "testofen",
    name: "Testofen",
    category: "男性",
    area: "男性更年期・男性健康",
    summary: "更年期男性の健康に向けた差別化された機能性素材。フェヌグリーク種子抽出物。",
    intake: "600mg/day",
    image: "/images/ingredients/testofen.webp",
    origin: ["ホロパ(フェヌグリーク)種子抽出物 Trigonella foenum-graecum", "インド産・韓国個別認定型素材"],
    healthClaims: [
      "更年期男性の健康(男性ホルモンであるテストステロンの恒常性維持および向上)に役立つ",
      "ホルモン分泌不足による男性更年期の緩和に役立つ",
    ],
    featurePoints: [
      "43歳〜75歳男性対象、12週間のヒト適用試験",
      "男性更年期症状(精神・心理の安定、身体機能の向上、性機能の向上)の大幅な改善",
      "韓国国内の男性更年期関連素材の中で最も高いAMSデータを保有",
      "米国で最も普及している男性健康原料",
      "更年期男性向けの追加臨床データを保有",
      "臨床データ(12週, Rao A et al. The Aging Male. 2016 Jun;19(2):134-42): AMS総点・身体機能・性機能のすべてでプラセボを上回る改善",
    ],
    evidenceTags: ["個別認定型素材", "12週間ヒト臨床試験", "AMS指標"],
    line: "Nature-derived Ingredients",
  },
  {
    id: "thinkgin",
    name: "ThinkGIN",
    category: "記憶",
    area: "記憶・認知機能",
    summary: "記憶力・認知機能改善に役立つ、一般紅参より高濃度のジンセノサイドを含む新芽人参抽出粉末。",
    intake: "450mg/day",
    image: "/images/ingredients/thinkgin.webp",
    origin: ["新芽人参抽出粉末 Panax ginseng C.A. Meyer sprout", "韓国産・韓国個別認定型素材"],
    healthClaims: [
      "記憶力および認知機能の改善に役立つ",
      "一般紅参対比で圧倒的なジンセノサイドを含有",
    ],
    featurePoints: [
      "55歳〜75歳男女対象、12週間のヒト適用試験",
      "記憶保存能力の強化",
      "神経細胞の炎症抑制",
      "睡眠の質、睡眠効率の増加",
      "シナプス可塑性の増加(記憶力と学習能力の向上)",
      "即時想起力の増加",
      "記憶力低下関連血液指標AChEの減少(プラセボ対比有意差, p<0.05)",
      "臨床データ: SVLT即時想起点数変化でプラセボ対比有意な増加(総点P<0.01、2次試行P<0.05)、PSQI-Kの睡眠潜時スコア改善(p<0.05)",
    ],
    evidenceTags: ["ヒト臨床試験", "記憶・睡眠", "ジンセノサイド高含有"],
    line: "Nature-derived Ingredients",
  },
  {
    id: "neulearn",
    name: "Neu learn",
    category: "認知",
    area: "加齢関連認知機能",
    summary: "加齢により低下した認知機能の改善に役立つ、白キクラゲ酵素分解抽出物。",
    intake: "600-1,200mg/day",
    image: "/images/ingredients/neulearn.webp",
    origin: ["白キクラゲ酵素分解抽出物 Tremella fuciformis Beck-extract", "中国産・韓国個別認定型素材"],
    healthClaims: [
      "加齢により低下した認知機能の改善に役立つ",
      "大脳灰白質容積の増加をf-MRIで確認・検証",
    ],
    featurePoints: [
      "40歳〜65歳男女対象、12週間のヒト適用試験",
      "主観的記憶減退症状(SMCQ)の減少(600mg・1,200mgともにプラセボ対比有意差 P=0.007/P=0.002)",
      "短期記憶・遂行機能の改善(プラセボ対比 P=0.001)",
      "計画機能の改善(600mg P=0.08、1,200mg P=0.02)",
      "f-MRI(機能的磁気共鳴画像)で右側縁上回・右側中前頭回・右側頭頂回・左側被蓋の灰白質容積増加を確認",
    ],
    evidenceTags: ["f-MRI検証", "12週間ヒト臨床試験", "認知機能"],
    line: "Nature-derived Ingredients",
  },
  {
    id: "applephenon",
    name: "Applephenon",
    category: "体脂肪",
    area: "ダイエット・体脂肪",
    summary: "体脂肪低減に役立つ、ダイエット向けの代表的なロングセラー原料。未熟リンゴ抽出物。",
    intake: "600mg/day",
    image: "/images/ingredients/applephenon.webp",
    origin: ["未熟リンゴ抽出物(青リンゴポリフェノール)", "韓国産・韓国個別認定型素材"],
    healthClaims: ["体脂肪低減に役立つ"],
    featurePoints: [
      "20歳〜55歳男女対象、12週間のヒト適用試験",
      "未熟リンゴ250個分を濃縮する米国特許技術3種で生産された、圧倒的な高濃縮ポリフェノールを含有",
      "中性脂肪の抑制と排出による確実な体脂肪減少効果",
      "優れた体脂肪量減少効果",
      "臨床データ(Journal of Oleo Science 59(6)321-338(2010) / 56(8)417-428(2007)): 12週摂取でウエスト周囲径・BMI指数がプラセボ対比有意に減少、摂取終了後4週間も効果が持続、CT撮影で内臓脂肪量の減少を確認(体重・腰囲・臀囲・腹部内臓脂肪・総腹部脂肪面積の減少)",
    ],
    evidenceTags: ["体脂肪減少", "持続効果データ", "高濃縮ポリフェノール"],
    line: "Nature-derived Ingredients",
  },
  {
    id: "collagen",
    name: "Low-molecular Collagen Peptide AG",
    category: "肌",
    area: "皮膚水分・弾力",
    summary: "紫外線による皮膚ダメージからの皮膚健康維持、目元のしわ・肌の潤いに役立つ低分子コラーゲンペプチド。",
    intake: "1,000mg/day",
    image: "/images/ingredients/collagen.webp",
    origin: ["500Da以下の低分子コラーゲンペプチド", "パンガシウス(Pangasius)の魚皮由来ゼラチン", "韓国産・韓国個別認定型素材・韓国初の二重機能性素材"],
    healthClaims: [
      "紫外線による皮膚ダメージからの皮膚健康維持に役立つ",
      "肌の潤いに役立つ",
    ],
    featurePoints: [
      "30歳〜65歳女性対象、12週間のヒト適用試験",
      "明確な皮膚保湿の改善(46.229→48.245、対照群は48.121のまま横ばい)",
      "目元のしわ減少(肉眼評価・指標成分の両方で確認、専門家評価2.585→2.366、P<0.01)",
      "皮膚総弾力の改善(R2値 0.694→0.726、対照群は0.693で横ばい、P<0.001)",
      "皮膚の粗さ改善(Ra値 12.845→12.404、対照群は12.905→12.789)",
    ],
    evidenceTags: ["皮膚保湿", "弾力・しわ改善", "二重機能性素材"],
    line: "Nature-derived Ingredients",
  },
  {
    id: "dermania",
    name: "DermaNia",
    category: "肌",
    area: "しわ・保湿ケア",
    summary: "しわの生成抑制、皮膚水分量の維持に役立つマコモ(Wild rice)抽出物。",
    intake: "250mg/day",
    image: "/images/ingredients/dermania.webp",
    origin: ["マコモ抽出物 Zizania latifolia(Wild rice)", "韓国産・韓国個別認定型素材"],
    healthClaims: [
      "しわの生成抑制・しわケアに役立つ",
      "皮膚水分の増加・保湿強化に役立つ",
    ],
    featurePoints: [
      "成人女性対象、12週間のヒト適用試験",
      "しわ減少(12週摂取でプラセボ比 P<0.05)",
      "皮膚水分量の増加(プラセボ比 P<0.05、慶熙大学校皮膚バイオテクノロジーセンター実施)",
      "メカニズム: コラーゲン遺伝子を活性化しMMPs遺伝子を非活性化することで、しわ形成を抑制し保湿力を高める",
    ],
    evidenceTags: ["12週間ヒト臨床試験", "しわ・保湿改善", "皮膚健康"],
    line: "Nature-derived Ingredients",
  },
  {
    id: "agrimony",
    name: "Agrimony extract",
    category: "肝臓",
    area: "非アルコール性脂肪肝健康",
    summary: "非アルコール性脂肪肝の改善に役立つアグリモニー(仙鶴草)由来素材。",
    intake: "75mg/day",
    image: "/images/ingredients/agrimony.webp",
    origin: ["アグリモニー(仙鶴草)抽出物 Agrimonia pilosa", "韓国産・韓国個別認定型素材"],
    healthClaims: [
      "非アルコール性脂肪肝の改善に役立つ",
      "肝脂肪含量とALT・AST値の減少",
    ],
    featurePoints: [
      "19歳〜70歳男女対象、13週間のヒト適用試験",
      "ALT値の改善効果(ALTレベル ベースライン対比8週間で有意に減少、P=0.025)",
      "AST値の改善効果(P=0.002)",
      "脂肪肝指数(HSI)の改善(P=0.044)",
    ],
    evidenceTags: ["ALT/AST改善データ", "脂肪肝指数(HSI)", "肝健康"],
    line: "Nature-derived Ingredients",
  },
  {
    id: "pinitol",
    name: "Pinitol",
    category: "肝臓",
    area: "肝健康・血糖健康",
    summary: "非アルコール性脂肪肝の改善、肝健康・血糖健康に役立つキャロブ由来素材。",
    intake: "肝健康 300mg/day・血糖健康 1.2g/day",
    image: "/images/ingredients/pinitol.webp",
    origin: ["キャロブ(Carob)の鞘から抽出・精製", "韓国産・韓国個別認定型素材"],
    healthClaims: [
      "非アルコール性脂肪肝の改善に役立つ",
      "肝の中性脂肪・コレステロールの減少に役立つ",
    ],
    featurePoints: [
      "脂肪肝のある成人60名対象、12週間のヒト適用試験",
      "損傷した肝細胞の改善・増加効果",
      "肝の中性脂肪細胞の減少とサイズの縮小",
      "臨床データ: 肝脂肪含量 12週間で17.9%→15.2%に減少(P=0.010)、ALT/AST値の減少(ALT P=0.030、AST P=0.018/P=0.040)",
      "抗酸化活性酵素GPxの増加(P=0.015)、酸化ストレス指標MDAの減少(P=0.002)",
    ],
    evidenceTags: ["脂肪肝改善データ", "GPx/MDA改善データ", "血糖健康"],
    line: "Nature-derived Ingredients",
  },
  {
    id: "acetobeta",
    name: "Aceto Beta",
    category: "二日酔い",
    area: "アルコール代謝サポート",
    summary: "アセトアルデヒドを速やかに分解し、飲酒による肝負担と二日酔いの軽減に優れた効果を持つ大豆発酵酢培養物。",
    intake: "1,000mg/day",
    image: "/images/ingredients/acetobeta.webp",
    origin: ["大豆発酵食酢培養物(酢酸菌 Acetic acid bacteria由来)"],
    healthClaims: ["アセトアルデヒドを速やかに分解し、飲酒による肝負担と二日酔いの軽減に優れた効果"],
    featurePoints: [
      "20代〜40代成人40名対象のヒト適用試験",
      "飲酒後のすっきりした朝の実感をサポート",
      "ADH(アルコール脱水素酵素)の増加による血中アルコール濃度の減少",
      "ALDH(アセトアルデヒド脱水素酵素)の増加による二日酔いの軽減",
      "臨床データ(Journal of Agriculture & Life Science. 2016,50,223-31): 飲酒0.25時間後の血中アセトアルデヒド変化量がプラセボ対比5倍の差、吐き気の改善効果 約70%(13名中9名)",
    ],
    evidenceTags: ["ADH/ALDHデータ", "飲酒後ケア", "発酵素材"],
    line: "Nature-derived Ingredients",
  },
  {
    id: "immulink",
    name: "Immulink MBG",
    category: "免疫",
    area: "免疫機能",
    summary: "自然免疫と獲得免疫の両方の向上に役立つ霊芝(レイシ)菌糸体抽出粉末。",
    intake: "200mg/day",
    image: "/images/ingredients/immulink.webp",
    origin: ["霊芝菌糸体抽出粉末 Ganoderma lucidum mycelium extract powder", "米国産・韓国個別認定型素材"],
    healthClaims: [
      "免疫機能の増進に役立つ",
      "自然免疫・獲得免疫の両方の改善効果を実証",
    ],
    featurePoints: [
      "18歳〜55歳男女対象、13週間のヒト適用試験",
      "特許取得済みの超音波抽出技術",
      "自然免疫・獲得免疫の両方で8種の免疫因子の有意な改善を確認(Foods 2023, 12(3), 659. doi:10.3390/foods12030659)",
      "獲得免疫: 総リンパ球数・T細胞(CD3+)・補助T細胞(CD4+)・細胞傷害性T細胞(CD8+)・CD4/CD8比・血清IgAグロブリン濃度の増加",
      "自然免疫: NK細胞数・NK細胞細胞傷害活性の増加",
      "高含有量のβ-グルカン(77%以上)",
      "構造的特徴: β-1,3および1,6の短い鎖とアセチル化などの複雑な鎖構造",
      "熱安定性(〜261℃)、pH安定性(pH1-11)、無味・無臭",
      "グローバル認証・登録: 韓国・米国(FDA GRAS)・欧州(EFSA)・台湾・中国・マレーシア・タイ・メキシコ登録、有機認証、Non-GMO、グルテンフリー、コーシャ(Kosher)・ハラル(HALAL)認証",
    ],
    evidenceTags: ["β-グルカン77%以上", "自然・獲得免疫8因子改善", "超音波抽出技術"],
    line: "Nature-derived Ingredients",
  },
];

export const evidenceItems = [
  { label: "Human clinical trial referenced", title: "ヒト臨床試験資料", value: "Application-specific" },
  { label: "SCI paper referenced", title: "SCI論文参照", value: "Evidence-led" },
  { label: "International patent referenced", title: "国際特許資料", value: "Strain-level" },
  { label: "KFDA individually recognized", title: "KFDA個別認定型素材", value: "Supplier" },
  { label: "FDA GRAS / NDI / USP referenced", title: "FDA GRAS / NDI / USP", value: "Bifidobacterium" },
  { label: "HALAL / KOSHER referenced", title: "HALAL / KOSHER", value: "Referenced" },
  { label: "ODM/OEM capable", title: "ODM/OEM対応", value: "Korea network" },
  { label: "Japan B2B network", title: "日本B2B展開", value: "Distribution" },
];

export const businessServices: Array<{
  title: string;
  copy: string;
  icon: LucideIcon;
}> = [
  {
    title: "Ingredient Sourcing",
    copy: "用途別の機能性素材、特許菌株、自然由来素材を日本市場の企画に合わせて選定します。",
    icon: FlaskConical,
  },
  {
    title: "ODM/OEM Production",
    copy: "韓国主要メーカーとの生産ネットワークを活用し、ブランド専用商品の開発を支援します。",
    icon: Factory,
  },
  {
    title: "Brand Royalty",
    copy: "iHEALブランドの活用や共同商品化を含めたロイヤリティモデルを検討します。",
    icon: BadgeCheck,
  },
  {
    title: "Sales & Marketing",
    copy: "日本側の販売会社、卸、メーカーに向けたB2B提案と市場導入を設計します。",
    icon: TrendingUp,
  },
  {
    title: "Distributor Supply",
    copy: "ディストリビューター、製造会社、卸売会社への安定供給体制を組み立てます。",
    icon: Network,
  },
  {
    title: "New Business Discovery",
    copy: "機能性ヘルスケア領域での新規事業、カテゴリー拡張、共同開発を探索します。",
    icon: Handshake,
  },
];

export const filterCategories = [
  "All",
  "女性",
  "体脂肪",
  "脳・記憶",
  "記憶",
  "認知",
  "肝臓",
  "鼻",
  "ストレス",
  "腸",
  "肌",
  "二日酔い",
  "免疫",
  "男性",
];

export const routeStages = [
  {
    title: "KOREA",
    kicker: "韓国",
    subtitle: "研究開発・製造",
    points: ["素材開発・ソーシング", "メーカー直供給", "製造・量産対応", "ブランド管理"],
  },
  {
    title: "BIOLAB Japan",
    kicker: "事業ブリッジ",
    subtitle: "日韓ヘルスケア事業連携",
    points: ["規制を踏まえた調整", "機能性素材ポートフォリオ", "ODM/OEM企画", "ブランドロイヤリティ"],
  },
  {
    title: "JAPAN",
    kicker: "日本",
    subtitle: "B2B展開",
    points: ["販売・マーケティング", "販売会社・メーカー・卸への供給", "販売ネットワーク拡大", "新規事業の発掘"],
  },
];

export const scrollLabSteps = [
  {
    title: "Evidence",
    ruby: "根拠資料",
    copy: "ヒト臨床試験、SCI論文、特許、認証資料を整理し、用途別の根拠構造を明確にします。",
    icon: ShieldCheck,
  },
  {
    title: "Ingredient",
    ruby: "機能性素材",
    copy: "プロバイオティクスと自然由来機能性素材を、ターゲットカテゴリーに合わせて選定します。",
    icon: Sprout,
  },
  {
    title: "Formulation",
    ruby: "処方設計",
    copy: "ODM/OEM対応を前提に、摂取量、剤形、訴求領域、表示表現を実務レベルで設計します。",
    icon: FlaskConical,
  },
  {
    title: "Supply",
    ruby: "生産供給",
    copy: "韓国メーカーの生産ネットワークと供給条件をつなぎ、事業化に必要な供給線を整えます。",
    icon: BriefcaseBusiness,
  },
  {
    title: "Market",
    ruby: "市場展開",
    copy: "日本側の販売会社、メーカー、卸売会社へ展開するB2B導入プランを構築します。",
    icon: Leaf,
  },
];

export const heroLabels = ["MED01", "MED02", "NVP-2106", "NVP-1702", "NVP-1703", "NVP-1704", "BGN4", "BORI", "AD011", "ThinkGIN"];
